package com.balatro.engine.codegen;

import com.balatro.engine.joker.def.Condition;
import com.balatro.engine.joker.def.Effect;
import com.balatro.engine.joker.def.JokerDef;
import com.balatro.engine.joker.def.Selector;
import com.balatro.engine.joker.def.Value;
import com.balatro.engine.state.RulesetBundle;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.databind.JsonNode;

import java.lang.reflect.ParameterizedType;
import java.lang.reflect.RecordComponent;
import java.lang.reflect.Type;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Generates a TypeScript client library from the engine's own type model — the concrete payoff of the
 * "single source of truth" architecture. The volatile, drift-prone part is generated by <b>reflection</b>,
 * so it can never disagree with the server:
 * <ul>
 *   <li>The closed vocabulary unions ({@code ConditionType}/{@code EffectType}/…) are read from the
 *       {@code @JsonSubTypes} discriminators the server scorer dispatches on — the exact set the client's
 *       preview interpreter must handle (the preview-mirror invariant, now mechanically enforced).</li>
 *   <li>The {@code RulesetBundle} interface is reflected from its record components.</li>
 * </ul>
 * The data envelopes ({@code JokerDef}/{@code Rule}) are discriminated-union shapes the client narrows on
 * {@code type}. This emits only TYPES + a content manifest — never the interpreter, which stays authoritative
 * on the server and preview-only on the client.
 */
public final class ClientCodegen {

    private ClientCodegen() {}

    /** The compiled content artifacts the client ships alongside these types. */
    private static final List<String> MANIFEST = List.of(
            "rulesets/vanilla.json",
            "rulesets/bmp-0.4.2-ranked.json",
            "content/decks.json",
            "content/bosses.json",
            "content/tags.json",
            "content/vouchers.json",
            "content/consumables.json",
            "rulesets/bundles/vanilla-solo.json",
            "rulesets/bundles/vanilla-pvp.json",
            "rulesets/bundles/bmp-0.4.2-ranked.json");

    public static String generate() {
        StringBuilder sb = new StringBuilder();
        sb.append("// GENERATED by com.balatro.engine.codegen.ClientCodegen — do not edit by hand.\n");
        sb.append("// Regenerate: ./gradlew test --tests com.balatro.engine.RulesetArtifactsTest -Dregen=true\n\n");

        union(sb, "ConditionType", Condition.class);
        union(sb, "EffectType", Effect.class);
        union(sb, "ValueType", Value.class);
        union(sb, "SelectorType", Selector.class);

        sb.append("/** A node tagged by its discriminator; the client narrows on `type` to read the rest. */\n");
        sb.append("export type Condition = { type: ConditionType } & Record<string, unknown>;\n");
        sb.append("export type Effect = { type: EffectType } & Record<string, unknown>;\n");
        sb.append("export type Value = { type: ValueType } & Record<string, unknown>;\n\n");

        sb.append("export interface Rule {\n");
        sb.append("  when: string;\n");
        sb.append("  condition?: Condition;\n");
        sb.append("  effects: Effect[];\n");
        sb.append("}\n\n");

        sb.append("export interface JokerDef {\n");
        for (RecordComponent rc : JokerDef.class.getRecordComponents()) {
            sb.append("  ").append(rc.getName()).append(": ").append(jokerFieldType(rc)).append(";\n");
        }
        sb.append("}\n\n");

        // Shared value types referenced by content records (a Modify on a game Var; a boss face-down rule).
        record(sb, "Modify", com.balatro.engine.joker.def.Modify.class);
        record(sb, "FaceDownRule", com.balatro.engine.game.BossBlind.FaceDownRule.class);

        // Content records: each compiles to a JSON table the client renders; the interface types it.
        record(sb, "RulesetBundle", RulesetBundle.class);
        record(sb, "DeckType", com.balatro.engine.game.DeckCatalog.DeckType.class);
        record(sb, "BossBlind", com.balatro.engine.game.BossBlind.class);
        record(sb, "Tag", com.balatro.engine.game.TagCatalog.Tag.class);
        record(sb, "Voucher", com.balatro.engine.game.VoucherCatalog.Voucher.class);
        record(sb, "Consumable", com.balatro.engine.consumable.Consumable.class);
        enumType(sb, "StakeName", com.balatro.engine.state.Stake.class);

        // Card + blind render primitives — the closed enums the client needs to draw cards and blinds.
        enumType(sb, "Suit", com.balatro.engine.card.Suit.class);
        enumType(sb, "Rank", com.balatro.engine.card.Rank.class);
        enumType(sb, "Edition", com.balatro.engine.card.Edition.class);
        enumType(sb, "Seal", com.balatro.engine.card.Seal.class);
        enumType(sb, "Enhancement", com.balatro.engine.card.Enhancement.class);
        enumType(sb, "ConsumableKind", com.balatro.engine.consumable.ConsumableType.class);
        enumType(sb, "BlindType", com.balatro.engine.game.Blinds.BlindType.class);

        sb.append("export const CONTENT_MANIFEST = [\n");
        for (String m : MANIFEST) sb.append("  \"").append(m).append("\",\n");
        sb.append("] as const;\n");
        return sb.toString();
    }

    /** A string-literal union of a sealed vocabulary's {@code @JsonSubTypes} discriminator names. */
    private static void union(StringBuilder sb, String tsName, Class<?> vocab) {
        JsonSubTypes st = vocab.getAnnotation(JsonSubTypes.class);
        String members = Arrays.stream(st.value())
                .map(JsonSubTypes.Type::name)
                .sorted()
                .map(n -> "\"" + n + "\"")
                .collect(Collectors.joining("\n  | "));
        sb.append("/** ").append(Arrays.stream(st.value()).count())
          .append(" discriminators the server dispatches on — the client must handle exactly these. */\n");
        sb.append("export type ").append(tsName).append(" =\n  | ").append(members).append(";\n\n");
    }

    /** A string-literal union of an enum's constant names (e.g. the stake ladder). */
    private static void enumType(StringBuilder sb, String tsName, Class<?> e) {
        String members = Arrays.stream(e.getEnumConstants())
                .map(c -> "\"" + c + "\"").collect(Collectors.joining(" | "));
        sb.append("export type ").append(tsName).append(" = ").append(members).append(";\n\n");
    }

    /** A TS interface reflected from a record's components (scalars/lists/enums only). */
    private static void record(StringBuilder sb, String tsName, Class<?> rec) {
        sb.append("export interface ").append(tsName).append(" {\n");
        for (RecordComponent rc : rec.getRecordComponents()) {
            sb.append("  ").append(rc.getName()).append(": ").append(tsType(rc.getGenericType())).append(";\n");
        }
        sb.append("}\n\n");
    }

    /** JokerDef's polymorphic fields point at the generated envelopes; the rest map structurally. */
    private static String jokerFieldType(RecordComponent rc) {
        return switch (rc.getName()) {
            case "rules" -> "Rule[]";
            case "handMods", "mods" -> "Record<string, unknown>[]";
            case "runMod", "copy" -> "Record<string, unknown> | null";
            default -> tsType(rc.getGenericType());
        };
    }

    private static String tsType(Type t) {
        if (t instanceof Class<?> c) {
            if (c == String.class) return "string";
            if (c == boolean.class || c == Boolean.class) return "boolean";
            if (c == int.class || c == long.class || c == double.class || c == float.class
                    || c == Integer.class || c == Long.class || c == Double.class) return "number";
            if (c == JsonNode.class) return "unknown";
            // the generated discriminated-union envelopes, so a boss's debuff/requires types correctly
            if (c == Condition.class) return "Condition";
            if (c == Effect.class) return "Effect";
            if (c == Value.class) return "Value";
            if (c == com.balatro.engine.joker.def.Modify.class) return "Modify";
            if (c == com.balatro.engine.game.BossBlind.FaceDownRule.class) return "FaceDownRule";
            if (c.isEnum()) {
                return Arrays.stream(c.getEnumConstants()).map(e -> "\"" + e + "\"")
                        .collect(Collectors.joining(" | "));
            }
            if (c.isArray()) return tsType(c.getComponentType()) + "[]";
            return "unknown";
        }
        if (t instanceof ParameterizedType pt) {
            Class<?> raw = (Class<?>) pt.getRawType();
            if (List.class.isAssignableFrom(raw)) return tsType(pt.getActualTypeArguments()[0]) + "[]";
            if (java.util.Map.class.isAssignableFrom(raw)) return "Record<string, unknown>";
        }
        return "unknown";
    }
}
